kind: Deployment
apiVersion: apps/v1
metadata:
  name: test02
spec:
  template:
    metadata:
      labels:
        app: test02
    spec:
      containers:
      - name: test02
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/test02:latest
  selector:
    matchLabels:
      app: test02
---
kind: Service
apiVersion: v1
metadata:
  name: test02
spec:
  type: LoadBalancer
  selector:
    app: test02
  ports:
  - name: http
    port: 5002
    targetPort: 3002
